# Generated by Django 5.0 on 2023-12-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_x_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='y',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.x'),
        ),
    ]
