# Generated by Django 5.0 on 2023-12-12 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_v_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='v',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='testapp.w'),
        ),
    ]
